import Nav from './components/nav/nav';
import Footer from './components/footer/footer';
import { Analytics } from '@vercel/analytics/react';

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <meta name="naver-site-verification" content="c52f35e4f46faadc684cde98b05b551ace43a16b" />
      </head>
      <body>
        <Nav />
        {children}
        <Analytics />
        <Footer />
      </body>
    </html>
  );
}
